name: Go Build and Compress

on:
  push:
    branches: [ "main" ]
    paths:
      - 'go/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./go

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.4'
          cache-dependency-path: go/go.sum

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build Binary
        run: |
          go build -ldflags="-s -w" -o tgbot main.go

      - name: Compress with UPX
        run: upx --best --lzma my_parser

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compressed-binary
          path: go/tgbot
